import { type InvoiceGenerationData } from "@/lib/validations/invoice-generation";
import { Text, View } from "@react-pdf/renderer";
import { memo } from "react";
import { PDF_DEFAULT_TEMPLATE_STYLES } from "./invoice-pdf-template";

interface InvoiceFooterProps {
  invoiceData: InvoiceGenerationData;
}

export const InvoiceFooter = memo(function InvoiceFooter({
  invoiceData,
}: InvoiceFooterProps) {
  return (
    <View style={[PDF_DEFAULT_TEMPLATE_STYLES.mt4]}>
      {/* Notes Section */}
      {invoiceData.notes && invoiceData.notesFieldIsVisible && (
        <View style={[PDF_DEFAULT_TEMPLATE_STYLES.mb3]}>
          <Text style={[PDF_DEFAULT_TEMPLATE_STYLES.subheader]}>Notes</Text>
          <Text
            style={[
              PDF_DEFAULT_TEMPLATE_STYLES.wrappedText,
              PDF_DEFAULT_TEMPLATE_STYLES.mt2,
            ]}
          >
            {invoiceData.notes || "[No notes]"}
          </Text>
        </View>
      )}

      {/* Signature Fields */}
      <View
        style={[
          PDF_DEFAULT_TEMPLATE_STYLES.flexRow,
          PDF_DEFAULT_TEMPLATE_STYLES.mt5,
        ]}
      >
        {/* Person Authorized to Issue */}
        {invoiceData.personAuthorizedToIssueFieldIsVisible && (
          <View style={[{ width: "48%" }]}>
            <View
              style={[
                PDF_DEFAULT_TEMPLATE_STYLES.borderT,
                PDF_DEFAULT_TEMPLATE_STYLES.mt5,
                PDF_DEFAULT_TEMPLATE_STYLES.pt2,
              ]}
            >
              <Text
                style={[
                  PDF_DEFAULT_TEMPLATE_STYLES.smallText,
                  PDF_DEFAULT_TEMPLATE_STYLES.centerAlign,
                ]}
              >
                Person Authorized to Issue
              </Text>
            </View>
          </View>
        )}

        {/* Spacer */}
        <View style={[{ width: "4%" }]} />

        {/* Person Authorized to Receive */}
        {invoiceData.personAuthorizedToReceiveFieldIsVisible && (
          <View style={[{ width: "48%" }]}>
            <View
              style={[
                PDF_DEFAULT_TEMPLATE_STYLES.borderT,
                PDF_DEFAULT_TEMPLATE_STYLES.mt5,
                PDF_DEFAULT_TEMPLATE_STYLES.pt2,
              ]}
            >
              <Text
                style={[
                  PDF_DEFAULT_TEMPLATE_STYLES.smallText,
                  PDF_DEFAULT_TEMPLATE_STYLES.centerAlign,
                ]}
              >
                Person Authorized to Receive
              </Text>
            </View>
          </View>
        )}
      </View>

      {/* Footer Note */}
      <View
        style={[
          PDF_DEFAULT_TEMPLATE_STYLES.mt5,
          PDF_DEFAULT_TEMPLATE_STYLES.centerAlign,
        ]}
      >
        <Text
          style={[PDF_DEFAULT_TEMPLATE_STYLES.smallText, { color: "#666" }]}
        >
          Generated by Invoice Manager
        </Text>
      </View>
    </View>
  );
});
